### PR TITLE
Extract the cross size calculation

### PR DESCRIPTION
**Pull request by thagikura**
This PR extracts the calculation to determine the cross size of the flex container from FlexboxLayout to FlexboxHelper to reuse it from FlexboxLayoutManager.

### CODE REVIEW

**Comment by thagikura** [comment]
@yaraki could you have a look for extracting the calculation on the cross size?

**Comment by yaraki** [comment]
It seems to me that this change makes it no longer possible for library users to create a custom component that implements FlexContainer because FlexboxHelper expects FlexboxContainerInternal (no one will actually do it, though). Is that correct?
If so, can you remind me why FlexContainer needed to be public?

**Comment by thagikura** [comment]
Yes, that's correct. The reason I made FlexContainer as public is for the demo app to treat FlexboxLayout and FlexboxLayoutManager equally to reduce the duplicate code.
And I didn't expect external developers to use FlexboxHelper to create their own FlexContainer implementation (actually FlexboxHelper is package private regardless of the FlexContainer visibility)

**Comment by yaraki** [comment]
Does that mean that FlexboxContainer will remain as a public class that is actually not useful for library users?

**Comment by thagikura** [comment]
Yes, that's the plan. But we could make the FlexContainer as package private and change the package name of the demo app accordingly instead.
Hmm, maybe it's more preferable given that FlexContainer isn't useful for external developers.

**Comment by yaraki** [comment]
Yes, that seems a better approach.

If the demo is the only one that needs to refer to both components in a seamless manner, it should be in the demo, not the library. That way, the demo will need to implement wrapper around the two components, but it actually feels cleaner to me.

Anyway, that's beyond the scope of this CL. I think it is OK to leave this to some time later (but before releasing a new version).

+2 for the CL content.

**Comment by thagikura** [comment]
Ok, actually the abstraction layer for the two components (FlexboxLayout and FlexboxLayoutManager) needs to be in the library, because some library code (FlexboxHelper) needs to treat the two components in a seamless manner.

But visibility of the FlexContainer should be considered further as discussed.
Left the note as part of the part of the LayoutManager implementation project https://github.com/google/flexbox-layout/projects/1

Submitting this CL for now.
Thanks for the detailed review!

**Pull request merged**
