### PR TITLE
Fixed issue #474

### PR DESCRIPTION
**Pull request by KryptKode**
canScrollHorizontally() throws NPE if the RecyclerView is not attached to the Window

### CODE REVIEW

**Review by simple272 — APPROVED** [review]

**Comment by bgorkowy** [comment]
Hi @KryptKode,
Why hasn't it been merged? Can we get this fix published @thagikura ?

**Comment by thagikura** [comment]
Sorry for the delay on this. LGTM!

**Comment by bgorkowy** [comment]
@thagikura Can you publish 1.1.1 version?

**Comment by PaulinaSadowska** [comment]
@thagikura We also have this problem in our app :( I would really appreciate it if you release this change

**Comment by thagikura** [comment]
Released the library as 1.1.1. Please let me know if something goes wrong.

**Comment by TDXCHANGE** [comment]
1e147f562fbbf1e2a83361bf7ffeffead0808818

**Pull request merged**
